"""english column names

Revision ID: 39a811f7c0e7
Revises: 3967aaf0c25a
Create Date: 2020-04-17 23:24:26.189314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a811f7c0e7'
down_revision = '3967aaf0c25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(length=4000), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_lastname'), ['lastname'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_phone'), ['phone'], unique=True)
        batch_op.drop_index('ix_player_nachname')
        batch_op.drop_index('ix_player_ort')
        batch_op.drop_index('ix_player_telefon')
        batch_op.drop_index('ix_player_vorname')
        batch_op.drop_column('telefon')
        batch_op.drop_column('nachname')
        batch_op.drop_column('vorname')
        batch_op.drop_column('ort')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ort', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('vorname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('nachname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.VARCHAR(length=10), nullable=True))
        batch_op.create_index('ix_player_vorname', ['vorname'], unique=False)
        batch_op.create_index('ix_player_telefon', ['telefon'], unique=1)
        batch_op.create_index('ix_player_ort', ['ort'], unique=False)
        batch_op.create_index('ix_player_nachname', ['nachname'], unique=False)
        batch_op.drop_index(batch_op.f('ix_player_phone'))
        batch_op.drop_index(batch_op.f('ix_player_lastname'))
        batch_op.drop_index(batch_op.f('ix_player_firstname'))
        batch_op.drop_index(batch_op.f('ix_player_city'))
        batch_op.drop_column('phone')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('comment')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
