"""user table

Revision ID: d3802a52912a
Revises: 
Create Date: 2020-04-02 04:05:08.465270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3802a52912a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=64), nullable=True),
    sa.Column('nachname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=10), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=60), nullable=True),
    sa.Column('jersey_size', sa.String(length=10), nullable=True),
    sa.Column('jersey_print', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_jersey_print'), 'user', ['jersey_print'], unique=False)
    op.create_index(op.f('ix_user_jersey_size'), 'user', ['jersey_size'], unique=False)
    op.create_index(op.f('ix_user_nachname'), 'user', ['nachname'], unique=False)
    op.create_index(op.f('ix_user_ort'), 'user', ['ort'], unique=False)
    op.create_index(op.f('ix_user_plz'), 'user', ['plz'], unique=False)
    op.create_index(op.f('ix_user_telefon'), 'user', ['telefon'], unique=True)
    op.create_index(op.f('ix_user_vorname'), 'user', ['vorname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vorname'), table_name='user')
    op.drop_index(op.f('ix_user_telefon'), table_name='user')
    op.drop_index(op.f('ix_user_plz'), table_name='user')
    op.drop_index(op.f('ix_user_ort'), table_name='user')
    op.drop_index(op.f('ix_user_nachname'), table_name='user')
    op.drop_index(op.f('ix_user_jersey_size'), table_name='user')
    op.drop_index(op.f('ix_user_jersey_print'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
