"""Rename users to players

Revision ID: e4ff146131a4
Revises: d3802a52912a
Create Date: 2020-04-15 19:13:31.037034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ff146131a4'
down_revision = 'd3802a52912a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=64), nullable=True),
    sa.Column('nachname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=10), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=60), nullable=True),
    sa.Column('jersey_size', sa.String(length=10), nullable=True),
    sa.Column('jersey_print', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_player_jersey_print'), 'player', ['jersey_print'], unique=False)
    op.create_index(op.f('ix_player_jersey_size'), 'player', ['jersey_size'], unique=False)
    op.create_index(op.f('ix_player_nachname'), 'player', ['nachname'], unique=False)
    op.create_index(op.f('ix_player_ort'), 'player', ['ort'], unique=False)
    op.create_index(op.f('ix_player_plz'), 'player', ['plz'], unique=False)
    op.create_index(op.f('ix_player_telefon'), 'player', ['telefon'], unique=True)
    op.create_index(op.f('ix_player_vorname'), 'player', ['vorname'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_jersey_print', table_name='user')
    op.drop_index('ix_user_jersey_size', table_name='user')
    op.drop_index('ix_user_nachname', table_name='user')
    op.drop_index('ix_user_ort', table_name='user')
    op.drop_index('ix_user_plz', table_name='user')
    op.drop_index('ix_user_telefon', table_name='user')
    op.drop_index('ix_user_vorname', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vorname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('nachname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefon', sa.VARCHAR(length=10), nullable=True),
    sa.Column('plz', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ort', sa.VARCHAR(length=60), nullable=True),
    sa.Column('jersey_size', sa.VARCHAR(length=10), nullable=True),
    sa.Column('jersey_print', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_vorname', 'user', ['vorname'], unique=False)
    op.create_index('ix_user_telefon', 'user', ['telefon'], unique=1)
    op.create_index('ix_user_plz', 'user', ['plz'], unique=False)
    op.create_index('ix_user_ort', 'user', ['ort'], unique=False)
    op.create_index('ix_user_nachname', 'user', ['nachname'], unique=False)
    op.create_index('ix_user_jersey_size', 'user', ['jersey_size'], unique=False)
    op.create_index('ix_user_jersey_print', 'user', ['jersey_print'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_player_vorname'), table_name='player')
    op.drop_index(op.f('ix_player_telefon'), table_name='player')
    op.drop_index(op.f('ix_player_plz'), table_name='player')
    op.drop_index(op.f('ix_player_ort'), table_name='player')
    op.drop_index(op.f('ix_player_nachname'), table_name='player')
    op.drop_index(op.f('ix_player_jersey_size'), table_name='player')
    op.drop_index(op.f('ix_player_jersey_print'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
